### ISSUE TITLE
Issue while generating an image 

### ISSUE THREAD

**Issue by mr-wh1tehat** [JaviToro/telegram-dalle-bot#1]
(node:127935) UnhandledPromiseRejectionWarning: Error: Request failed with status code 401
    at createError (/home/ubuntu/image-ai-bot/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/ubuntu/image-ai-bot/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/ubuntu/image-ai-bot/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:127935) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:127935) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by JaviToro** [comment]
Hey, thanks for the report, but I'm not sure this is something related to my code. In any case, I can't take a look at it by the moment, so I'm closing this issue.
